spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://emh-mysql:3306/EnglishMasteryHub}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
app:
  jwt:
    jwtSecret: UUY+YA4e6vDzHgfhxype+S5J9AwQKC8P0NXGLK9gV+OUB4a9g2liqCvruzMUrSYe
    jwtExpirationMs: 21600000
    jwtRefreshExpirationMs: 86400000
  resource:
    handler: /uploads/**
    path: /content/
  file:
    handler: /uploads/**
    path: /uploads/
    file-upload-uri: http://englishmasteryhub.online:8080/uploads/$FILE_NAME$
    file-upload-path: uploads/
    file-storage-uri: http://englishmasteryhub.online:8080/uploads/$FILE_NAME$
    file-storage-path: content/